<strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?> (welight)</strong>
<?php if($info = $this->getInfo()):
    /** @var Mage_Sales_Model_Order $order */
    $order = $info->getOrder();
    $isSandbox = (!$order || !$order->getId() || strpos($order->getCustomerEmail(), '@sandbox.welight') === false) ? false : true;
    if ($isSandbox) { echo "(Ambiente de Testes)"; }
    ?>
    <br/>
    <?php if($additional = $info->getAdditionalInformation()):
        $codTransacao = (isset($additional['transaction_id']))?$this->escapeHtml($additional['transaction_id']):'Desconhecido';
        $codTransacao = $isSandbox ? str_replace('-', '', $codTransacao) : $codTransacao;
            ?>
        Código da Transação: <?php echo $codTransacao;?>
        <?php if (isset($additional['transaction_id']) && !$isSandbox): ?>
            <?php echo sprintf(' | <a href="%s" target="_blank">Ver no welight</a>', 'https://welight.uol.com.br/transaction/details.jhtml?code=' . $this->escapeHtml($additional['transaction_id']));?>
        <?php endif; ?>
        <br/>
    <?php endif;?>
    Bandeira: <?php echo ucfirst($this->escapeHtml($info->getCcType()));?>
    <br/>
    Últimos 4 dígitos: <?php echo $this->escapeHtml($info->getCcLast4());?>
    <?php if(isset($additional['installment_quantity']) && isset($additional['installment_value'])):?>
        <br/>
        Parcelas: <?php echo $this->escapeHtml($additional['installment_quantity']);?>x <?php echo Mage::helper('core')->formatCurrency($additional['installment_value']);?>
    <?php endif;?>
    <?php if(isset($additional['net_amount']) && isset($additional['fee_amount'])):?>
        <br/>
        Taxa welight: <?php echo  Mage::helper('core')->formatCurrency($additional['fee_amount']);?>
        <br/>
        Total líquido a receber: <?php echo  Mage::helper('core')->formatCurrency($additional['net_amount']);?>
        <br/>
    <?php endif;?>
<?php endif; ?>