<?php
$_helper = Mage::helper('gatewaywelight');
?>
<script type="text/javascript">
    //<![CDATA[
    var preparewelight = function(){
        if(typeof RMwelightObj != "undefined"){
            <?php if ($_helper->isDebugActive()): ?>
			console.info('welight was already started.');
            <?php endif; ?>
            return;
		}
        <?php if ($_helper->isDebugActive()): ?>
        console.info('welight is initiating. Wait for ready message.');
        <?php endif; ?>
			RMwelightObj = new RMwelight(<?php echo $_helper->getConfigJs()?>);
			console.info('welight ready');

    }
    preparewelight();

    //]]>
</script>