<?php
/** @var Welight_Gateway_Block_Form_Redirect $this */
$_code=$this->getMethodCode();
$_redirModel = Mage::getModel('welight_gateway/payment_redirect');

# IWD Checkout compatibility fix
$iwdEnabled = method_exists(Mage::helper('welight_gateway'), 'isIwdEnabled') && Mage::helper('welight_gateway')->isIwdEnabled();
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="<?php echo (!$iwdEnabled)?'display:none;':'';?>">
    <li><?php echo $_redirModel->getStoreConfig('description');?></li>
</ul>