<?php
/**
 *
 * @category   Inovarti
 * @package    Welight_Gateway
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<img src="<?php echo $this->getSkinUrl('welight/images/welight-logo.png'); ?>" width="80" /><br />
<strong><?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?></strong>

<?php if($this->getInfo()): ?>
    <br />
    <?php echo $this->__('Invoice') ?>: <a href="#" onclick="return Iugu.load('<?php echo $this->getUrl('adminhtml/iugu_invoice/view', array('id' => $this->getInvoiceId())) ?>');"><?php echo $this->escapeHtml($this->getInvoiceId()) ?></a>
    <br />
    <?php echo $this->__('Installments') ?>: <?php echo $this->escapeHtml($this->getInstallmentDescription()) ?>
    <br />
<?php endif ?>
