<?php
// Retrieve order
    $_order = new Mage_Sales_Model_Order();
    $orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
    $_order->loadByIncrementId($orderId);
    if (Mage::getSingleton('customer/session')->isLoggedIn()) {
        // Get the customer object from customer session
        $customer = Mage::getSingleton('customer/session')->getCustomer();
        $customerID = $customer->getID();//get customer id
        $customerName = $customer->getName();//get customer full name
        $customerEmail = $customer->getEmail();//get customer email
    }
    // Get the id of the last order for the current user(session)
    $orderId = Mage::getSingleton('checkout/session')->getLastOrderId();        

    // If an order actually exists
    if ($orderId) {

        //Get the order details based on the order id ($orderId)
        $order = Mage::getModel('sales/order')->load($orderId);

        // Get the id of the orders shipping address
        $shippingId = $order->getShippingAddress()->getId();

        // Get shipping address data using the id
        $address = Mage::getModel('sales/order_address')->load($shippingId);
        $street = $address->getFormated(true);

        // Display the shipping address data array on screen
        var_dump($street);
        $_shippingAddress = $order->getShippingAddress();
        $streetFull = $_shippingAddress->getStreetFull();
        $region = $_shippingAddress->getRegion();
        $city = $_shippingAddress->getCity();
        $postcode = $_shippingAddress->getPostcode();
        $customerId = $_order->getCustomerId();
        var_dump($streetFull);
        var_dump($region);
        var_dump($city);
        var_dump($postcode);
        var_dump($customerId);

    }

    $store = Mage::app()->getStore(); // store info
    $configValue = Mage::getStoreConfig('payment/mygateway/token', $store);
    var_dump($configValue);
?>
<form name="mygatewayform" method="post" action="http://192.168.15.40:8080/checkout/">
	<input type="hidden" name="orderid" value="<?php echo $orderId; ?>">
    <input type="hidden" name="grandtotal" value="<?php echo $_order->getBaseGrandTotal(); ?>">

    <input name="configValue" value="<?php echo $configValue; ?>">

    <input name="email" value="<?php echo $customerEmail; ?>">
    <input name="street" value="<?php echo $street; ?>">

    <input name="streetFull" value="<?php echo $streetFull; ?>">
    <input name="region" value="<?php echo $region; ?>">
    <input name="city" value="<?php echo $city; ?>">
    <input name="postcode" value="<?php echo $postcode; ?>">
    <input name="customerId" value="<?php echo $customerId; ?>">
</form>
<script type="text/javascript">
//document.mygatewayform.submit();
</script>