<?php
/**
 *
 * @category   Inovarti
 * @package    Welight_Gateway
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?>

<?php if($this->getInvoiceUrl()): ?>
<br />
<a href="<?php echo $this->getInvoiceUrl() ?>" target="_blank"><?php echo $this->__('Click here to print your Boleto') ?></a>
<?php endif ?>

<?php echo $this->getChildHtml()?>
